config/routes.rb
RetroRails::Application.routes.draw do

  get "user/index"

  root :to => "home#index"

  resources :users do
    resources :retrospectives
  end

  resources :teams

  resources :retrospectives do
    resources :goods     , :controller => "retrospectives/goods" do
      collection { get :similar_retro_items }
    end
    resources :bads      , :controller => "retrospectives/bads" do
      collection { get :similar_retro_items }
    end
    resource :invitations, :controller => "retrospectives/invitations"
  end

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "retrospectives/bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "retrospectives/bads#to_good", as: :retrospective_bad_to_good

  get "/retrospectives/send_email/:id" => "retrospectives#send_email", as: :retrospective_send_email
  get "/retrospectives/preview_email/:id" => "retrospectives#preview_email", as: :retrospective_preview_email

  get "/team/members/:id" => "teams#members", as: :show_members

  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  match "/signup"           => "users#new"
  match "/signin"            => "users#authenticate"
  match "/logout"            => "users#logout"
  match "/password"          => "users#password"
  match "/password_update"   => "users#password_update"

  match "/remember_password"          => "remember_password#index"
  match "/remember_password/remember" => "remember_password#remember_password"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :logged_at, :name, :team_id, :password, :password_confirmation, :forgot_password_token, :role

  belongs_to :team

  before_create :encrypt_password

  validates :email,    :presence =>true, :uniqueness=>true
  validates :name,     :presence =>true
  validates :team_id,  :presence =>true
  validates :password, :presence =>true, :length => { :minimum => 5, :maximum => 40 }, :confirmation => true

  USER_PROJECTS = ["Core", "WebStore", "Aplicativos"]

  def self.md5(text)
    Digest::MD5.hexdigest(text)
  end

  def encrypt_password
    if password.present?
      self.password = Digest::MD5.hexdigest(self.password)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password == md5(password)
      user
    end
  end

  def generate_forgot_password_token
    self.forgot_password_token = generate_digest_token
  end

  def admin?
    self.role == 'admin'
  end

  private

  def generate_digest_token
    Digest::SHA1.hexdigest(SecureRandom.base64)
  end

end

app/controllers/users_controller.rb
# encoding : utf-8
class UsersController < ApplicationController

  before_filter :ensure_authentication, :only => [:edit, :update, :destroy, :index, :show]
  before_filter :ensure_correct_user, :only => [:edit, :update]

  def index
    @users = User.order(:team_id, :name, :role)
    @teams = Team.order(:name)
    @new_user = User.new
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @teams = Team.order(:name)
    render layout: false
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @teams = Team.order(:name)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /password
  def password
    if params[:forgot_password_token].present?
      @user = User.where(forgot_password_token: params[:forgot_password_token]).first
    else
      @user = current_user
    end
  end

  def password_update
    if params[:user][:forgot_password_token].present?
      @user = User.where(forgot_password_token: params[:user][:forgot_password_token]).first
    else
      @user = current_user
    end
    @user.password = User.md5(params[:user][:password])
    @user.password_confirmation = User.md5(params[:user][:password_confirmation])

    respond_to do |format|
      if !params[:user][:password].blank? and @user.save
        session[:user_id] = @user.id
        @user.reload
        @user.forgot_password_token = nil
        @user.save
        format.html { redirect_to "/retrospectives", notice: 'Sua senha foi alterada!' }
      else
        format.html { render action: "password", notice: 'Suas senhas não conferem!' }
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @teams = Team.order(:name)
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = 'Seu usuário foi criado com sucesso!'
      redirect_to root_path
    else
      flash[:error] = "Less!! #{@user.errors.full_messages}"
      render action: "new", layout: false
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @teams = Team.order(:name)
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to "/retrospectives", notice: 'Seu dados foram atualizados!' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def authenticate
    user = User.authenticate(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to "/retrospectives", notice: "Olá #{user.name}, bem vindo ao Retrospectiba!"
    else
      redirect_to root_url, notice: 'Usuário ou senha inválida'
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_url, :alert => "Obrigado por ter usado o Retrospectiba!"
  end

  def ensure_correct_user
    raise TentandoSerEspertaoException  if !current_user.admin? && session[:user_id].to_s != params[:id].to_s
  end

  class TentandoSerEspertaoException < StandardError
  end
end

app/helpers/users_helper.rb
# encoding : utf-8
module UsersHelper

  ROLES = { admin: 'Administrador', team_leader: 'Líder de Time', po: 'PO', user: 'Usuário', ct: 'CT', qa: 'QA', analist: 'Analista' }

  def role_name(role)
    return ROLES[role.to_sym]
  end

  def can_edit?
    ['team_leader', 'admin'].include?(@current_user.role)
  end

  def base_url
    request.base_url
  end
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: "nav-form"}) do |f| %>

  <% if @user.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Atenção!</h4>
      Os seguintes erros foram encontrados:
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="form">
    <li class="field">
      <label>Nome </label>
      <%= f.text_field :name, placeholder:"Nome", class: "span8" %>
    </li>
    <li class="field">
      <label>Email </label>
      <%= f.text_field :email, placeholder:"Email", class: "span8" %>
    </li>
    <li class="field">
      <label>Time </label>
      <%= f.collection_select(:team_id, @teams, :id, :name) %>
    </li>
    <li class="field">
      <label>Senha </label>
      <%= f.password_field :password, placeholder:"Senha", class: "password_field" %>
    </li>
    <li class="field">
      <label>Confirmação de Senha </label>
      <%= f.password_field :password_confirmation, placeholder:"Confirmação", class: "password_field" %>
    </li>

    <%= f.hidden_field :role, value: "user" %>

    <li class="field">
      <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
    </li>
  </ul>
<% end %>

app/views/users/_new_user.html.erb
<%= form_for @new_user do |u| %>
  <div id="newUser" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Novo Usuário</h2>
    </div>
    <div class="modal-body">
    <% if @new_user.errors.any? %>
      <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Atenção!</h4>Os seguintes erros foram encontrados:
          <ul>
          <% @new_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
    <% end %>
      <div class="field">
        <span class="span3">Nome</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.text_field :name, class: "span5" %>
        </div>
      </div>
      <div class="field">
        <span class="span3">Email</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.text_field :email, class: "span5" %>
        </div>
      </div>
      <div class="field">
        <span class="span3">Time</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.collection_select(:team_id, @teams, :id, :name) %>
        </div>
      </div>
      <div class="field">
        <span class="span3">Senha</span>
      </div>
      <div class="field">
        <div class="span3 input-append">
          <%= u.password_field :password, class: "password_field" %>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <%= u.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Perfil</b></li>
</ul>
<div class="row-fluid">
  <div class="span5">
    <img src="/assets/nelson.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span10 -->
  <div class="span6">
    <h3><%= @user.name %></h3>
    <legend></legend>
    <%= form_for(@user, html: {class: "nav-form"}) do |f| %>

      <% if @user.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <ul class="form">
        <li class="field">
          <label>Nome </label>
          <%= f.text_field :name, placeholder:"Nome", class: "span8" %>
        </li>
        <li class="field">
          <label>Email </label>
          <%= f.text_field :email, placeholder:"Email", class: "span8" %>
        </li>
        <li class="field">
          <label>Time </label>
          <%= f.collection_select(:team_id, @teams, :id, :name) %>
        </li>
        <% if @current_user.admin? %>
          <li class="field">
            <label>Papel </label>
            <%= select_tag("user[role]", options_for_select([ ['Selecione um nível', ''], ['Administrador', 'admin'], ['Líder de Time', 'team_leader'], ['PO', 'po'], ['Usuário', 'user'], ['CT', 'ct'], ['QA', 'qa'], ['Analista', 'analist'] ], @user.role))%>
          </li>
        <% end %>
        <li class="field">
          <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
        </li>
      </ul>
    <% end %>
  </div><!-- div:span3 -->
</div><!-- div:row -->

app/views/users/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, users_path %> <span class="divider">/</span></li>
  <li><b>Usuários</b></li>
</ul>
<div class="row-fluid">
  <div class="span6">
    <div class="page-header">
      <h3>Usuários</h3>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Email</th>
          <th>Time</th>
          <th>Papel</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, edit_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td><%= user.team.name %></td>
            <td><%= user.role ? role_name(user.role) : "" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
      <a href="#newUser" role="button" class="btn btn-inverse btn-large" data-toggle="modal">Novo usuário</a>
    <br />

  </div><!-- div:span6 -->
  <div class="span5">
    <img src="/assets/bart.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span6 -->
</div><!-- div:row -->


<%= render 'new_user' %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fosformol</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-40782711-1', 'retrospectiba.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body id="home">
    <div class="container">
      <div class="hero-unit">
        <div class="page-header">
          <div class="row-fluid">
            <ul class="breadcrumb">
              <li><%= link_to 'Retrospectiba', root_path, class: "btn btn-link" %><span class="divider">/</span></li>
              <li><b>Novo Usuário</b></li>
            </ul>
            <div class="span5">
              <img src="/assets/homer-smart.png"/>
            </div><!-- /div:span5 -->
            <div class="span6">
              <h3>Cadastre-se.</h3>
              <legend></legend>
              <%= render 'form' %>
              <div class="controls">
                <span class="help-block">Você <span class="label label-important">não</span> receberá um e-mail para ativar sua conta.</span>
              </div><!-- div.controls -->
            </div><!-- /div:span2 -->
          </div><!-- div:page-header -->
        </div><!-- div.row-fluid -->
      </div><!--/div:hero-unit-->
    </div><!-- /div:container-->
    <footer>
      <div class="container">
        <p>
          <span class="label label-info">www.retrospectiba.com</span>
          <span class="label label-important"><a href="https://github.com/zekitow/retro/network/members" target="_blank">contribuidores</a></span>
        </p>
      </div><!-- /div:container-->
    </footer>
  </body>
</html>

app/views/users/password.html.erb
<ul class="breadcrumb">
  <li><%= link_to @user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Alterar Senha</b></li>
</ul>
<div class="row-fluid">
  <div class="span6">
    <img src="/assets/willy.png"  title="<%= @user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span10 -->
  <div class="span5">
    <h3><%= @user.name %></h3>
    <legend></legend>
    <p>Não esqueça de anotar sua nova senha.</p>
    <%= form_for(@user, url: password_update_path, html: {class: "nav-form"}) do |f| %>
      <% if @user.errors.any? or notice %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.password_field :password, placeholder:"Password", class: "span5"  %>
      </div>
      <div class="field">
        <%= f.password_field :password_confirmation, placeholder:"Confirmação", class: "span5"  %>
      </div>
      <div class="field">
        <%= f.hidden_field :forgot_password_token, class: "span5", value: @user.forgot_password_token  %>
      </div>
      <div class="actions">
        <%= f.submit "Salvar", class: "btn btn-primary btn-inverse" %>
        <% unless @user %>
        <%= link_to 'Voltar', root_path, class: "btn btn-link" %>
        <% end %>
      </div>
    <% end %>
  </div><!-- div:span3 -->
</div><!-- div:row -->

app/views/users/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><%= link_to 'Retrospectivas', retrospectives_path %> <span class="divider">/</span></li>
  <li><b><%= @user.name %></b></li>
</ul>
<div class="alert alert-error hide" id="retrospectives-alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="alert alert-success hide" id="retrospectives-alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="page-header">
      <h3><%= @user.name %></h3>
    </div>
  </div><!--/div:span5 -->
</div><!-- div:row -->

app/views/users/signup.html.erb
<h1>Cadastre-se</h1>

<%= render 'form' %>