config/routes.rb
RetroRails::Application.routes.draw do

  get "user/index"

  root :to => "home#index"

  resources :users do
    resources :retrospectives
  end

  resources :teams

  resources :retrospectives do
    resources :goods     , :controller => "retrospectives/goods" do
      collection { get :similar_retro_items }
    end
    resources :bads      , :controller => "retrospectives/bads" do
      collection { get :similar_retro_items }
    end
    resource :invitations, :controller => "retrospectives/invitations"
  end

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "retrospectives/bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "retrospectives/bads#to_good", as: :retrospective_bad_to_good

  get "/retrospectives/send_email/:id" => "retrospectives#send_email", as: :retrospective_send_email
  get "/retrospectives/preview_email/:id" => "retrospectives#preview_email", as: :retrospective_preview_email

  get "/team/members/:id" => "teams#members", as: :show_members

  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  match "/signup"           => "users#new"
  match "/signin"            => "users#authenticate"
  match "/logout"            => "users#logout"
  match "/password"          => "users#password"
  match "/password_update"   => "users#password_update"

  match "/remember_password"          => "remember_password#index"
  match "/remember_password/remember" => "remember_password#remember_password"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /home
  # GET /home.json
  def index
    if session[:user_id]
      redirect_to retrospectives_path
    else
      render layout: false
    end
  end
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retrospectiba</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-40782711-1', 'retrospectiba.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body id="home">
    <div class="container">
      <div class="hero-unit">
        <a href="https://github.com/zekitow/retro" target="_blank">
          <img class="fork-me" src="https://s3.amazonaws.com/github/ribbons/forkme_left_red_aa0000.png" alt="Fork me on GitHub">
        </a>
        <div class="page-header">
          <div class="row-fluid">
            <div class="span3"><img src="/assets/homer.png" title="Doh!"/> </div>
            <div class="span9">
              <h1>Retrospectiba</h1>
              <h2>Não esqueça o que rolou na última retro!</h1>
              <form class="form-inline" action="/signin" method="POST">
                <legend></legend>
                <% if flash[:notice] %>
                  <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <h4>Obrigado!</h4>
                    <%=flash[:notice]%>
                  </div>
                <% end %>
                <% if flash[:error] %>
                  <div class="alert alert-error">
                    <button type="button" class="close" data-dismiss="alert">x</button>
                    <h4>Ooops!</h4>
                    <%=flash[:error]%>
                  </div>
                <% end %>
                <div class="control-group">
                  <div class="controls">
                    <input type="text" placeholder="E-mail" class="span4" name="email"/>
                  </div><!-- div.controls -->
                </div><!-- div.control-group -->
                <div class="control-group">
                  <div class="controls">
                    <input type="password" placeholder="Password"  class="span3" name="password"/>
                    <button type="submit" class="btn btn-inverse">Login</button>
                  </div><!-- div.controls -->
                </div><!-- div.control-group -->
                <div class="control-group">
                  <div class="controls">
                    <span class="help-block">Lembrar senha <%= link_to 'Clique aqui', remember_password_path %>.</span>
                  </div><!-- div.controls -->
                </div><!-- div.control-group -->
                <div class="control-group">
                  <div class="controls">
                    <span class="help-block">Não tenho uma conta, mas quero me <%= link_to 'cadastrar', signup_path %>.</span>
                  </div><!-- div.controls -->
                </div><!-- div.control-group -->
              </form>
            </div><!-- div:span10 -->
          </div><!-- div.row-fluid -->
        </div><!-- div:page-header -->
      </div><!--/div:hero-unit-->
    </div><!-- /div:container-->
    <footer>
      <div class="container">
        <p>
          <span class="label label-info">www.retrospectiba.com</span>
          <span class="label label-important"><a href="https://github.com/zekitow/retro/network/members" target="_blank">contribuidores</a></span>
        </p>
      </div><!-- /div:container-->
    </footer>
  </body>
</html>