config/routes.rb
RetroRails::Application.routes.draw do

  get "user/index"

  root :to => "home#index"

  resources :users do
    resources :retrospectives
  end

  resources :teams

  resources :retrospectives do
    resources :goods     , :controller => "retrospectives/goods" do
      collection { get :similar_retro_items }
    end
    resources :bads      , :controller => "retrospectives/bads" do
      collection { get :similar_retro_items }
    end
    resource :invitations, :controller => "retrospectives/invitations"
  end

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "retrospectives/bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "retrospectives/bads#to_good", as: :retrospective_bad_to_good

  get "/retrospectives/send_email/:id" => "retrospectives#send_email", as: :retrospective_send_email
  get "/retrospectives/preview_email/:id" => "retrospectives#preview_email", as: :retrospective_preview_email

  get "/team/members/:id" => "teams#members", as: :show_members

  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  match "/signup"           => "users#new"
  match "/signin"            => "users#authenticate"
  match "/logout"            => "users#logout"
  match "/password"          => "users#password"
  match "/password_update"   => "users#password_update"

  match "/remember_password"          => "remember_password#index"
  match "/remember_password/remember" => "remember_password#remember_password"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/models/retrospective.rb
class Retrospective < ActiveRecord::Base
  attr_accessible :name, :start_at, :finish_at, :team_id, :target

  belongs_to :team

  has_many :goods
  has_many :bads

  validates :name, :team_id, :target, presence: true
  validates :start_at , presence: true, if: :finish_at?
  validates :finish_at, presence: true, if: :start_at?
end

app/controllers/retrospectives/bads_controller.rb
class Retrospectives::BadsController < ApplicationController
  before_filter :ensure_authentication

  def index
    @retrospective = Retrospective.find(params[:retrospective_id])
    render 'retrospectives/_list_bads', layout: false
  end

  def create
    bad = Bad.new(params[:bad])
    bad.user = current_user
    if bad.valid?
      bad.save
    else
      flash[:error] = bad.errors.full_messages
    end
    redirect_to retrospective_path(params[:retrospective_id])
  end

  def keep
    bad = Bad.find(params[:id])
    bad.retrospective_id = params[:retrospective_id]
    bad.keep!
    raise RuntimeError, 'Erro ao salvar post-it' unless bad.save
    redirect_to retrospective_path(params[:retrospective_id])
  end

  def to_good
    bad = Bad.find(params[:id])
    good = Good.new
    good.retrospective_id = params[:retrospective_id]
    good.description = "Corrigido: #{bad.description}!"
    good.save
    bad.destroy
    redirect_to retrospective_path(params[:retrospective_id])
  end

  def destroy
    bad = Bad.find(params[:id])
    bad.destroy
    respond_to do |format|
      format.json { render :json => bad }
    end
  end

  def update
    bad = Bad.find(params[:id])
    if bad.update_attributes(params[:bad])
      head :ok
    else
      head :error
    end
  end

  def similar_retro_items
    search_words  = params[:q].split(' ').select {|word| word.size > 2}.uniq
    results_array = {}

    search_words.each do |word|
      Bad.where('retrospective_id = ? AND description LIKE (?)', params[:retrospective_id], "%#{word}%").collect do |item|
        results_array[item] = results_array[item].to_i + 1
      end
    end

    @retro_items = results_array.sort_by {|item, quantity| quantity}.reverse

    head :not_found and return if @retro_items.blank?
    render template: 'retrospectives/similar_retro_items', layout: false
  end
end

app/controllers/retrospectives/goods_controller.rb
class Retrospectives::GoodsController < ApplicationController
  before_filter :ensure_authentication

  def index
    @retrospective = Retrospective.find(params[:retrospective_id])
    render 'retrospectives/_list_goods', layout: false
  end

  def create
    good = Good.new(params[:good])
    good.user = current_user
    if good.valid?
      good.save
    else
      flash[:error] = good.errors.full_messages
    end
    redirect_to retrospective_path(params[:retrospective_id])
  end

  def destroy
    good = Good.find(params[:id])
    good.destroy
    respond_to do |format|
       format.json { render :json => good }
    end
  end

  def update
    good = Good.find(params[:id])
    if good.update_attributes(params[:good])
      head :ok
    else
      head :error
    end
  end

  def similar_retro_items
    search_words  = params[:q].split(' ').select {|word| word.size > 2}.uniq
    results_array = {}

    search_words.each do |word|
      Good.where('retrospective_id = ? AND description LIKE (?)', params[:retrospective_id], "%#{word}%").collect do |item|
        results_array[item] = results_array[item].to_i + 1
      end
    end

    @retro_items = results_array.sort_by {|item, quantity| quantity}.reverse

    head :not_found and return if @retro_items.blank?
    render template: 'retrospectives/similar_retro_items', layout: false
  end
end

app/controllers/retrospectives/invitations_controller.rb
class Retrospectives::InvitationsController < ApplicationController

  before_filter :ensure_authentication

  def new
    @retrospective = Retrospective.find(params[:retrospective_id])
  end

  def create
    retrospective = Retrospective.find(params[:retrospective_id])
    users_id = params[:users_id]
    retrospective.invited_users.delete_all
    users_id.each { |user_id| retrospective.invited_users << User.find(user_id)}
    redirect_to user_retrospectives_path(@current_user)
  end

end

app/controllers/retrospectives_controller.rb
# encoding : utf-8
class RetrospectivesController < ApplicationController

  before_filter :ensure_authentication

  # GET /retrospectives
  # GET /retrospectives.json
  def index
    @user = current_user

    conditions = ""

    conditions += "team_id =  #{@user.team_id} "            if !@user.admin?
    conditions += "team_id =  #{params[:team_id]} "         if !params[:team_id].blank?
    conditions += " AND "                                   if !conditions.blank? && !params[:retro_name].blank?
    conditions += "name    like '%#{params[:retro_name]}%'" if !params[:retro_name].blank?

    @teams = Team.find(:all, conditions: !@user.admin? ? "user_id = #{@user.id}" : "", order: :name)

    @retrospectives = Retrospective.find(:all, conditions: conditions, order: "start_at desc")

    @retrospective = Retrospective.new
  end

  def create
    retrospective = Retrospective.new(params[:retrospective])

    if retrospective.save
      flash[:notice] = 'Sua nova retro foi criada!'
    else
      flash[:error] = retrospective.errors.full_messages
    end

    redirect_to retrospectives_path
  end

  def update
    @retrospective = Retrospective.find(params[:id])
    @retrospective.update_attributes(params[:retrospective])
    head :ok
  end

  # GET /retrospectives
  # GET /retrospectives.json
  def show
    @retrospective = Retrospective.find(params[:id])
    @worst = Retrospective.where("id < #{params[:id]} and team_id = '#{@retrospective.team_id}'").order('created_at desc').first
    @good = Good.new
    @bad  = Bad.new
  end

  def preview_email
    @retrospective = Retrospective.find(params[:id])
    @worst = Retrospective.where(:id => params[:id]).first
    render '/retrospective_mailer/retrospective_resume.html.erb', :layout => 'mail'
  end

  def send_email
    begin
      RetrospectiveMailer.retrospective_resume(params[:id]).deliver
      flash[:notice] = 'Mensagem enviada com sucesso'
    rescue
      flash[:error] = 'Um erro ocorreu! Abra um chamado aê, leke!'
    end

    redirect_to retrospective_path(params[:id])
  end
end

app/views/retrospectives/_delete_bads.html.erb
<%= form_for([@retrospective, @bad], {remote: true, method: :delete, html: {name: "delete_bad", id: "delete_bad"}}) do |f| %>
    <div id="delete-bad" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Excluir Registro</h4>
      </div>
      <div class="modal-body">
        <p>Tem certeza que deseja apagar o registro?</p>
      </div>
      <div class="modal-footer">
        <%= f.submit "Excluir", class: "btn btn-primary", type: "submit" %>
      </div>
    </div>
<% end %>

app/views/retrospectives/_delete_goods.html.erb
<%= form_for([@retrospective, @good], {remote: true, method: :delete, html: {name: "delete_good", id: "delete_good"}}) do |f| %>
    <div id="delete-good" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4>Excluir Registro</h4>
      </div>
      <div class="modal-body">
        <p>Tem certeza que deseja apagar o registro?</p>
      </div>
      <div class="modal-footer">
        <%= f.submit "Excluir", class: "btn btn-primary", type: "submit" %>
      </div>
    </div>
<% end %>

app/views/retrospectives/_list_bads.html.erb
<% @retrospective.bads.each do |item| %>
  <tr class="bad" id="bad-<%= item.id %>">
    <td class="bad-desc"><%= best_in_place item, :description, type: :input, path: retrospective_bad_path(item.retrospective, item) %></td>
    <td class="bad-action"><%= best_in_place item, :action, type: :input, path: retrospective_bad_path(item.retrospective, item) %></td>
    <td id="<%= item_votes_id(item) %>" class="votes"><%= item.votes %></td>
    <td><%= link_to '', vote_up_url(model: item.class.to_s.downcase, id: item.id), remote: true, method: :post, class: 'icon-thumbs-up', name: "bad-#{item.id}" %></td>
    <td><%= link_to '', vote_down_url(model: item.class.to_s.downcase, id: item.id), remote: true, method: :delete, class: 'icon-thumbs-down' %></td>
    <td>
      <input type="hidden" value="<%= item.id %>" />
      <%= link_to '', '#delete-bad', class: 'icon-remove btn-delete-bad', 'data-toggle' => 'modal' %>
    </td>
  </tr>
<% end %>

app/views/retrospectives/_list_goods.html.erb
<% @retrospective.goods.each do |item| %>
  <tr class="good" id="good-<%= item.id %>">
    <td class="good-desc"><%= best_in_place item, :description, type: :input, path: retrospective_good_path(@retrospective, item) %></td>
    <td id="<%= item_votes_id(item) %>"class="votes"><%= item.votes %></td>
    <td><%= link_to '', vote_up_url(model: item.class.to_s.downcase, id: item.id), remote: true, method: :post, class: 'icon-thumbs-up', name: "good-#{item.id}" %></td>
    <td><%= link_to '', vote_down_url(model: item.class.to_s.downcase, id: item.id), remote: true, method: :delete, class: 'icon-thumbs-down' %></td>
    <td>
      <input type="hidden" value="<%= item.id %>" />
      <%= link_to '', '#delete-good', class: 'icon-remove btn-delete-good', 'data-toggle' => 'modal' %>
    </td>
  </tr>
<% end %>

app/views/retrospectives/_list_worst.html.erb
<% if @worst and @worst.bads.present? %>
  <div class="row-fluid">
    <div class="span12">
      <h4>Items da última retrospectiva:</h4>
      <table class="table">
        <thead>
          <tr>
            <th>Descrição</th>
            <th>Ação</th>
            <th width="100">Corrigido?</th>
          </tr>
        </thead>
        <tbody>
          <% @worst.bads.each do |bad| %>
            <tr class="warning">
              <td><%= bad.description %></td>
              <td><%= bad.action %></td>
              <% if can_edit? %>
                <td>
                  <%= link_to 'Sim',  retrospective_bad_to_good_path(@retrospective, bad), class: 'btn btn-small btn-success' %>
                  <%= link_to 'Não',  retrospective_bad_keeps_path(@retrospective, bad), class: 'btn btn-small btn-danger' %>
                </td>
              <% else %>
                <td>&nbsp;</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div><!--/div:span5 -->
  </div><!-- div:row -->
<% end %>

app/views/retrospectives/_new_bad.html.erb
<%= form_for([@retrospective, @bad]) do |f| %>
  <%= f.hidden_field :retrospective_id, :value => @retrospective.id %>
  <div id="addRuim" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Ruim</h2>
    </div>
    <div class="modal-body">
      <% if @bad.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
            <% @bad.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.text_field :description, placeholder: 'Descrição', class: 'span5 description', autocomplete: 'off' %>
      </div>
      <div class="well well-small similar bad">
        <button type="button" class="close">&times;</button>
        <ul class="nav nav-pills nav-stacked"></ul>
      </div>
      <div class="field">
        <%= f.text_field :action, placeholder:"Ação", class: "span5" %>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/_new_good.html.erb
<%= form_for([@retrospective, @good]) do |f| %>
  <%= f.hidden_field :retrospective_id, :value => @retrospective.id %>
  <div id="addBom" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Bom</h2>
    </div>
    <div class="modal-body">
      <% if @good.errors.any? %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Atenção!</h4>
          Os seguintes erros foram encontrados:
          <ul>
            <% @good.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.text_field :description, placeholder: 'Descrição', class: 'span5 description', autocomplete: 'off' %>
      </div>
      <div class="well well-small similar good">
        <button type="button" class="close">&times;</button>
        <ul class="nav nav-pills nav-stacked"></ul>
      </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/_new_retro.html.erb
<%= form_for @retrospective do |f| %>
    <div id="newRetro" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2>Nova Retrospectiva</h2>
    </div>
    <div class="modal-body">
        <% if @retrospective.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Atenção!</h4>
            Os seguintes erros foram encontrados:
            <ul>
              <% @retrospective.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field">
          <span class="span3">Descrição</span>
        </div>
        <div class="field">
          <div class="span3 input-append">
            <%= f.text_field :name, class: "span5", value: "Sprint# #{@retrospectives.count + 1}" %>
          </div>
        </div>
        <div class="field">
          <span class="span3">Objetivo do sprint</span>
        </div>
        <div class="field">
          <div class="span3 input-append">
            <%= f.text_field :target, class: "span5" %>
          </div>
        </div>
        <div class="field">
          <span class="span3">Time</span>
        </div>
        <div class="field">
          <div class="span3 input-append">
            <%= f.collection_select(:team_id, @teams, :id, :name) %>
          </div>
        </div>
        <div class="field">
          <span class="span3">Data inicio</span>
          <span class="span2">Data final</span>
        </div>
        <div class="field">
          <div class="span3 input-append">
            <%= f.text_field :start_at, class: "input-medium date", readonly: true %>
            <button class="btn_start_at btn" type="button"><span class="icon-calendar"></span></button>
          </div>
          <div class="span2 input-append">
            <%= f.text_field :finish_at, class: "input-medium date", readonly: true %>
            <button class="btn_finish_at btn" type="button"><span class="icon-calendar"></span></button>
          </div>
        </div>
    </div>
    <div class="modal-footer">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/retrospectives/_retro_search.html.erb
<div class="retro_search">
  <%= form_tag(retrospectives_path, method: :get) do  %>
    <%= text_field_tag :retro_name, params[:retro_name], class: 'span3' %>
    <% if @current_user.admin? %>
      <%= select_tag "team_id", options_from_collection_for_select(@teams, "id", "name", params[:team_id]), :prompt => 'Todos' %>
    <% end %>
    <%= submit_tag "Filtrar", class: "btn btn-primary btn-inverse" %>
  <% end %>
</div>

app/views/retrospectives/index.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><b>Retrospectivas</b></li>
</ul>
<div class="row-fluid">
  <div class="span6">
    <div class="page-header">
      <h3>Retrospectivas</h3>
    </div>

    <%= render 'retro_search' %>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Bom</th>
          <th>Ruim</th>
          <th>Início</th>
          <th>Término</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% @retrospectives.each do |retro| %>
          <tr>
            <td><%= link_to "#{retro.name}", retrospective_path(retro)  %></td>
            <td><%= retro.try(:goods).try(:count) %></td>
            <td><%= retro.try(:bads).try(:count) %></td>
            <td><%= retro.start_at ? retro.start_at.strftime("%d/%m/%Y") : "" %></td>
            <td><%= retro.finish_at ? retro.finish_at.strftime("%d/%m/%Y") : "" %></td>
            <td><%= retro.team.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% if can_edit? %>
      <a href="#newRetro" role="button" class="btn btn-inverse btn-large" data-toggle="modal">Nova Retrospectiva</a>
    <% end %>
    <br />

  </div><!-- div:span6 -->
  <div class="span5">
    <img src="/assets/moe.png"  title="<%= @current_user.name %>" alt="Ralph Steadman Artwork"/>
  </div><!-- div:span6 -->
</div><!-- div:row -->

<%= render 'new_retro' %>

app/views/retrospectives/new.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, users_path %> <span class="divider">/</span></li>
  <li><%= link_to "Retrospectivas", user_retrospectives_path(@current_user) %> <span class="divider">/</span></li>
  <li><b>Nova</b></li>
</ul>

<div class="page-header">
  <h3>Nova Retrospectiva</h3>
</div>
<%= form_for(@retrospective, html: {class: "nav-form"}) do |f| %>

  <% if @retrospective.errors.any? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>Atenção!</h4>
      Os seguintes erros foram encontrados:
      <ul>
      <% @retrospective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="control-group">
      <label class="control-label" for="inputEmail">Email</label>
      <div class="controls">
        <input type="text" id="inputEmail" placeholder="Email">
      </div>
    </div>
    Sprint #: <%= f.text_field :sprint_number, placeholder:"Número", class: "span8" %>
  </div>
<% end %>

app/views/retrospectives/show.html.erb
<ul class="breadcrumb">
  <li><%= link_to @current_user.name, retrospectives_path %> <span class="divider">/</span></li>
  <li><%= link_to 'Retrospectivas', retrospectives_path %> <span class="divider">/</span></li>
  <li><b><%= @retrospective.name %></b></li>
</ul>
<div class="alert alert-error hide" id="retrospectives-alert-error">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="alert alert-success hide" id="retrospectives-alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <h4></h4>
  <p></p>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="page-header">
      <% if can_edit? %>
        <div class="sprint-header">
          <h3><%= @retrospective.name %></h3>
          <%= link_to retrospective_send_email_path(@retrospective), :role => "button", :class => "btn btn-inverse btn-small btn-primary", "data-toggle" =>"modal" do %>
            <span class="icon-envelope"></span>
            Enviar
          <% end %>
        </div>
      <% end %>
      <% if @retrospective.start_at.present? %>
        <b>Início</b> <em><%= @retrospective.start_at.strftime("%d/%m/%Y") %></em>
        <b>Término</b> <em><%= @retrospective.finish_at.strftime("%d/%m/%Y") %></em>
        <b> | Time</b> <em><%= @retrospective.team.name %></em> <br>
        <b>Objetivo do sprint: </b> <em><%= (@retrospective.target) ? @retrospective.target : "Não possui objetivo" %></em>
      <% end %>
    </div>
  </div><!--/div:span5 -->
</div><!-- div:row -->
<%= render 'list_worst' %>
<div class="row-fluid list-goods-and-bads">
  <div class="span6">
    <h4><a href="#addBom" role="button" class="btn btn-small btn-success" data-toggle="modal">Bom</a></h4>
    <table class="table goods_table" data-url="<%= retrospective_goods_path(@retrospective) %>">
      <thead>
        <tr>
          <th>Descrição</th>
          <th width="20"></th>
        </tr>
      </thead>
      <tbody>
        <%= render 'list_goods' %>
      </tbody>
    </table>
  </div><!-- div:span6 -->
  <div class="span6">
    <h4><a href="#addRuim" role="button" class="btn btn-small btn-danger" data-toggle="modal">Ruim</a></h4>
    <table class="table bads_table" data-url="<%= retrospective_bads_path(@retrospective) %>">
      <thead>
        <tr>
          <th>Descrição</th>
          <th>Ação</th>
          <th width="20"></th>
        </tr>
      </thead>
      <tbody>
        <%= render 'list_bads' %>
      </tbody>
    </table>
  </div><!-- div:span6 -->
</div><!-- div:row -->

<%= render 'new_good' %>
<%= render 'new_bad' %>
<%= render 'delete_goods' %>
<%= render 'delete_bads' %>

app/views/retrospectives/similar_retro_items.html.erb
<li class="legend">Itens similares:</li>
<% @retro_items.each do |item, quantity| %>
  <% class_name = item.class.to_s.downcase %>
  <li class="item" data-id="<%= "#{class_name}-#{item.id}" %>">
    <%= link_to vote_up_url(model: class_name, id: item.id), remote: true, method: :post, class: 'icon-thumbs-up vote' do %>
      <br />
      <b><%= item.votes %></b>
    <% end %>
    <%= link_to "##{class_name}-#{item.id}", class: 'description' do %>
      <%= item.description %>
      <br />
      <% if class_name == 'bad' %>
        <small><%= item.action %></small>
      <% end %>
    <% end %>
  </li>
<% end %>