config/routes.rb
RetroRails::Application.routes.draw do

  get "user/index"

  root :to => "home#index"

  resources :users do
    resources :retrospectives
  end

  resources :teams

  resources :retrospectives do
    resources :goods     , :controller => "retrospectives/goods" do
      collection { get :similar_retro_items }
    end
    resources :bads      , :controller => "retrospectives/bads" do
      collection { get :similar_retro_items }
    end
    resource :invitations, :controller => "retrospectives/invitations"
  end

  get "/retrospectives/:retrospective_id/bads/:id/keep" => "retrospectives/bads#keep", as: :retrospective_bad_keeps
  get "/retrospectives/:retrospective_id/bads/:id/good" => "retrospectives/bads#to_good", as: :retrospective_bad_to_good

  get "/retrospectives/send_email/:id" => "retrospectives#send_email", as: :retrospective_send_email
  get "/retrospectives/preview_email/:id" => "retrospectives#preview_email", as: :retrospective_preview_email

  get "/team/members/:id" => "teams#members", as: :show_members

  post   "/votes/:model/:id" => "votes#create", as: :vote_up
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down
  delete "/votes/:model/:id" => "votes#destroy", as: :vote_down

  match "/signup"           => "users#new"
  match "/signin"            => "users#authenticate"
  match "/logout"            => "users#logout"
  match "/password"          => "users#password"
  match "/password_update"   => "users#password_update"

  match "/remember_password"          => "remember_password#index"
  match "/remember_password/remember" => "remember_password#remember_password"

  # Error 404 Handler
  match "*path" => "application#not_found"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retrospectiba</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-40782711-1', 'retrospectiba.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Retrospectiba', retrospectives_path, :class => "brand" %>
          <div class="nav-collapse">
            <ul class="nav pull-right">
              <li class="divider-vertical"></li>
              <% if @current_user %>
                <% if @current_user.role == "admin" %>
                  <li><%= link_to "Usuários", users_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Times", teams_path %></li>
                  <li class="divider"></li>
                <% end %>
                <li><%= link_to @current_user.name, edit_user_path(@current_user) %>
                  <li class="divider"></li>
                  <li><%= link_to "Alterar senha", password_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sair", logout_path %></li>
              <% end %>
            </ul><!-- /nav pull-right -->
          </div><!-- /div.nav-collapse -->
        </div>
      </div><!-- /div:container -->
    </div>
    <div class="container">
      <div class="content">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Yeah!</h4>
            <%=flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:error] %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4>Yeah!</h4>
            <%=flash[:error] %>
          </div>
        <% end %>
        <%= yield %>
      </div><!-- /div:content-->
    </div><!-- /div:container-->
    <footer>
      <div class="container">
        <br/>
        <p>
          <span class="label label-info">www.retrospectiba.com</span>
          <span class="label label-important"><a href="https://github.com/zekitow/retro/network/members" target="_blank">contribuidores</a></span>
        </p>
      </div><!-- /div:container-->
    </footer>
  </body>
  <%= javascript_include_tag 'application' %>
  <% if Dir.glob("app/assets/javascripts/#{params[:controller]}*").count > 0 %>
    <%= javascript_include_tag params[:controller] %>
  <% end %>
</html>

app/views/layouts/mail.html.erb
<%= yield %>